// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProj_L00172691.DataAccess;

#nullable disable

namespace MyProj_L00172691.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250125213206_loadData")]
    partial class loadData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyProj_L00172691.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Hiro Arikawa",
                            Genre = "Contemporary",
                            Title = "The Travelling Cat Chronicles"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Clair Keegan",
                            Genre = "Historical",
                            Title = "Small Things Like These"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jason Rekulak",
                            Genre = "Mystery",
                            Title = "Hidden Pictures"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Peter Beagle",
                            Genre = "Fantasy",
                            Title = "The Story of Kao Yu"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Barbara Comyns",
                            Genre = "Classics",
                            Title = "Who Was Changed and Who Was Dead"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
